name: janalytics_fluttify_example
description: Demonstrates how to use the janalytics_fluttify plugin.
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  decorated_flutter: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  janalytics_fluttify:
    path: ../

flutter:
  uses-material-design: true