include: package:pedantic/analysis_options.yaml

linter:
  rules:
    camel_case_types: false
    camel_case_extensions: false
    omit_local_variable_types: false
    prefer_single_quotes: false
    unnecessary_this: false