name: janalytics_fluttify
description: A `JAnalytics` Component, Powered By `Fluttify` Engine.
version: 0.2.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/janalytics_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  jcore_fluttify: ^0.2.0
  foundation_fluttify: ^0.9.5
  core_location_fluttify: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.janalytics_fluttify
        pluginClass: JanalyticsFluttifyPlugin
      ios:
        pluginClass: JanalyticsFluttifyPlugin