//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

package me.yohom.janalytics_fluttify;

import android.util.Log;

import java.util.HashMap;
import java.util.Map;

import androidx.annotation.NonNull;
import io.flutter.embedding.engine.plugins.FlutterPlugin;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.PluginRegistry.Registrar;

import static me.yohom.foundation_fluttify.FoundationFluttifyPluginKt.getEnableLog;
import static me.yohom.foundation_fluttify.FoundationFluttifyPluginKt.getHEAP;

@SuppressWarnings("ALL")
public class JanalyticsFluttifyPlugin implements FlutterPlugin, MethodChannel.MethodCallHandler {

    private BinaryMessenger messenger;

    private final Map<String, Handler> handlerMap = new HashMap<String, Handler>() {{
        // method
        put("cn.jiguang.analytics.android.view.BuryWebActivity::onBackPressed", (args, methodResult) -> {
            // args
        
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.view.BuryWebActivity ref = (cn.jiguang.analytics.android.view.BuryWebActivity) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.view.BuryWebActivity@" + refId + "::onBackPressed(" + "" + ")");
            }
        
            // invoke native method
            try {
                ref.onBackPressed();
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.agent.JMMIClick::clickOn", (args, methodResult) -> {
            // args
            // ref arg
            android.view.View var0 = (android.view.View) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.agent.JMMIClick::clickOn(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.agent.JMMIClick.clickOn(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.agent.JMMIClick::performClickTabLayoutTabView", (args, methodResult) -> {
            // args
            // ref arg
            android.view.View var0 = (android.view.View) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.agent.JMMIClick::performClickTabLayoutTabView(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.agent.JMMIClick.performClickTabLayoutTabView(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::getAccountId", (args, methodResult) -> {
            // args
        
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::getAccountId(" + "" + ")");
            }
        
            // invoke native method
            String result;
            try {
                result = ref.getAccountId();
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success(result);
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setCreationTime", (args, methodResult) -> {
            // args
            // jsonable arg
            Long var1 = (Long) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setCreationTime(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setCreationTime(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setSex", (args, methodResult) -> {
            // args
            // jsonable arg
            Integer var1 = (Integer) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setSex(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setSex(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setBirthdate", (args, methodResult) -> {
            // args
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setBirthdate(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setBirthdate(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setPaid", (args, methodResult) -> {
            // args
            // jsonable arg
            Integer var1 = (Integer) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setPaid(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setPaid(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setPhone", (args, methodResult) -> {
            // args
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setPhone(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setPhone(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setEmail", (args, methodResult) -> {
            // args
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setEmail(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setEmail(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setName", (args, methodResult) -> {
            // args
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setName(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setName(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setWechatId", (args, methodResult) -> {
            // args
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setWechatId(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setWechatId(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setQqId", (args, methodResult) -> {
            // args
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setQqId(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setQqId(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.Account::setWeiboId", (args, methodResult) -> {
            // args
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.Account ref = (cn.jiguang.analytics.android.api.Account) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.Account@" + refId + "::setWeiboId(" + var1 + ")");
            }
        
            // invoke native method
            try {
                ref.setWeiboId(var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.aop.JAct::onContentChanged", (args, methodResult) -> {
            // args
        
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.aop.JAct ref = (cn.jiguang.analytics.android.api.aop.JAct) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.aop.JAct@" + refId + "::onContentChanged(" + "" + ")");
            }
        
            // invoke native method
            try {
                ref.onContentChanged();
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.aop.JMMIAgent::clickOn", (args, methodResult) -> {
            // args
            // ref arg
            android.view.View var0 = (android.view.View) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.aop.JMMIAgent::clickOn(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.aop.JMMIAgent.clickOn(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.aop.JMMIAgent::onViewShow", (args, methodResult) -> {
            // args
            // ref arg
            android.view.View var0 = (android.view.View) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.aop.JMMIAgent::onViewShow(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.aop.JMMIAgent.onViewShow(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.aop.JMMIAgent::onViewHide", (args, methodResult) -> {
            // args
            // ref arg
            android.view.View var0 = (android.view.View) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.aop.JMMIAgent::onViewHide(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.aop.JMMIAgent.onViewHide(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.aop.JMMIAgent::performClickTabLayoutTabView", (args, methodResult) -> {
            // args
            // ref arg
            android.view.View var0 = (android.view.View) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.aop.JMMIAgent::performClickTabLayoutTabView(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.aop.JMMIAgent.performClickTabLayoutTabView(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::setDebugMode", (args, methodResult) -> {
            // args
            // jsonable arg
            boolean var0 = (boolean) args.get("var0");
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::setDebugMode(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.setDebugMode(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::init", (args, methodResult) -> {
            // args
            // ref arg
            android.content.Context var0 = (android.content.Context) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::init(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.init(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::onPageStart", (args, methodResult) -> {
            // args
            // ref arg
            android.content.Context var0 = (android.content.Context) getHEAP().get((int) args.get("var0"));
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::onPageStart(" + var0 + var1 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.onPageStart(var0, var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::onPageEnd", (args, methodResult) -> {
            // args
            // ref arg
            android.content.Context var0 = (android.content.Context) getHEAP().get((int) args.get("var0"));
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::onPageEnd(" + var0 + var1 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.onPageEnd(var0, var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::requestPermission", (args, methodResult) -> {
            // args
            // ref arg
            android.app.Activity var0 = (android.app.Activity) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::requestPermission(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.requestPermission(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::initCrashHandler", (args, methodResult) -> {
            // args
            // ref arg
            android.content.Context var0 = (android.content.Context) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::initCrashHandler(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.initCrashHandler(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::stopCrashHandler", (args, methodResult) -> {
            // args
            // ref arg
            android.content.Context var0 = (android.content.Context) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::stopCrashHandler(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.stopCrashHandler(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::identifyAccount__android_content_Context__cn_jiguang_analytics_android_api_Account__cn_jiguang_analytics_android_api_AccountCallback", (args, methodResult) -> {
            // args
            // ref arg
            android.content.Context var0 = (android.content.Context) getHEAP().get((int) args.get("var0"));
            // ref arg
            cn.jiguang.analytics.android.api.Account var1 = (cn.jiguang.analytics.android.api.Account) getHEAP().get((int) args.get("var1"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::identifyAccount(" + var0 + var1 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.identifyAccount(var0, var1, new cn.jiguang.analytics.android.api.AccountCallback() {
                // method channel
                MethodChannel callbackChannel = new MethodChannel(messenger, "cn.jiguang.analytics.android.api.JAnalyticsInterface::identifyAccount__android_content_Context__cn_jiguang_analytics_android_api_Account__cn_jiguang_analytics_android_api_AccountCallback::Callback");
        
                // call dart method
                @Override
                public void callback(int var1, String var2) {
                    // print log
                    if (getEnableLog()) {
                        Log.d("java-callback", "fluttify-java-callback: callback(" + var1 + var2 + ")");
                    }
        
                    // convert to jsonable data
                    // jsonable arg
                    int argvar1 = var1;
                    // jsonable arg
                    String argvar2 = var2;
        
                    // call dart method
                    callbackChannel.invokeMethod(
                            "Callback::cn.jiguang.analytics.android.api.AccountCallback::callback",
                            new HashMap<String, Object>() {{
                                put("var1", argvar1);
                                put("var2", argvar2);
                            }}
                    );
        
                    // method result
        
                }
        
            });
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::detachAccount__android_content_Context__cn_jiguang_analytics_android_api_AccountCallback", (args, methodResult) -> {
            // args
            // ref arg
            android.content.Context var0 = (android.content.Context) getHEAP().get((int) args.get("var0"));
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::detachAccount(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.detachAccount(var0, new cn.jiguang.analytics.android.api.AccountCallback() {
                // method channel
                MethodChannel callbackChannel = new MethodChannel(messenger, "cn.jiguang.analytics.android.api.JAnalyticsInterface::detachAccount__android_content_Context__cn_jiguang_analytics_android_api_AccountCallback::Callback");
        
                // call dart method
                @Override
                public void callback(int var1, String var2) {
                    // print log
                    if (getEnableLog()) {
                        Log.d("java-callback", "fluttify-java-callback: callback(" + var1 + var2 + ")");
                    }
        
                    // convert to jsonable data
                    // jsonable arg
                    int argvar1 = var1;
                    // jsonable arg
                    String argvar2 = var2;
        
                    // call dart method
                    callbackChannel.invokeMethod(
                            "Callback::cn.jiguang.analytics.android.api.AccountCallback::callback",
                            new HashMap<String, Object>() {{
                                put("var1", argvar1);
                                put("var2", argvar2);
                            }}
                    );
        
                    // method result
        
                }
        
            });
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::setAnalyticsReportPeriod__android_content_Context__int", (args, methodResult) -> {
            // args
            // ref arg
            android.content.Context var0 = (android.content.Context) getHEAP().get((int) args.get("var0"));
            // jsonable arg
            int var1 = (int) args.get("var1");
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::setAnalyticsReportPeriod(" + var0 + var1 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.setAnalyticsReportPeriod(var0, var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::setAnalyticsReportPeriod__int", (args, methodResult) -> {
            // args
            // jsonable arg
            int var0 = (int) args.get("var0");
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::setAnalyticsReportPeriod(" + var0 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.setAnalyticsReportPeriod(var0);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.JAnalyticsInterface::setChannel", (args, methodResult) -> {
            // args
            // ref arg
            android.content.Context var0 = (android.content.Context) getHEAP().get((int) args.get("var0"));
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // ref
        
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.JAnalyticsInterface::setChannel(" + var0 + var1 + ")");
            }
        
            // invoke native method
            try {
                cn.jiguang.analytics.android.api.JAnalyticsInterface.setChannel(var0, var1);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // method
        put("cn.jiguang.analytics.android.api.AccountCallback::callback", (args, methodResult) -> {
            // args
            // jsonable arg
            int var1 = (int) args.get("var1");
            // jsonable arg
            String var2 = (String) args.get("var2");
        
            // ref
            int refId = (int) args.get("refId");
            cn.jiguang.analytics.android.api.AccountCallback ref = (cn.jiguang.analytics.android.api.AccountCallback) getHEAP().get(refId);
        
            // print log
            if (getEnableLog()) {
                Log.d("fluttify-java", "fluttify-java: cn.jiguang.analytics.android.api.AccountCallback@" + refId + "::callback(" + var1 + var2 + ")");
            }
        
            // invoke native method
            try {
                ref.callback(var1, var2);
            } catch (Throwable throwable) {
                throwable.printStackTrace();
                if (getEnableLog()) {
                    Log.d("Current HEAP: ", getHEAP().toString());
                }
                methodResult.error(throwable.getMessage(), null, null);
                return;
            }
        
            // result
            methodResult.success("success");
        });
        // factory
        put("ObjectFactory::createcn_jiguang_analytics_android_view_BuryWebActivity__", (args, methodResult) -> {
            Log.d("ObjectFactory", "创建对象: cn_jiguang_analytics_android_view_BuryWebActivity__");
        
            // args
        
        
            // create target object
            cn.jiguang.analytics.android.view.BuryWebActivity obj = new cn.jiguang.analytics.android.view.BuryWebActivity();
            getHEAP().put(obj.hashCode(), obj);
        
            // print current HEAP
            if (getEnableLog()) {
                Log.d("ObjectFactory", "HEAP: " + getHEAP());
            }
        
            methodResult.success(obj.hashCode());
        });
        // factory
        put("ObjectFactory::createcn_jiguang_analytics_android_api_agent_JMMIDlgPupW__", (args, methodResult) -> {
            Log.d("ObjectFactory", "创建对象: cn_jiguang_analytics_android_api_agent_JMMIDlgPupW__");
        
            // args
        
        
            // create target object
            cn.jiguang.analytics.android.api.agent.JMMIDlgPupW obj = new cn.jiguang.analytics.android.api.agent.JMMIDlgPupW();
            getHEAP().put(obj.hashCode(), obj);
        
            // print current HEAP
            if (getEnableLog()) {
                Log.d("ObjectFactory", "HEAP: " + getHEAP());
            }
        
            methodResult.success(obj.hashCode());
        });
        // factory
        put("ObjectFactory::createcn_jiguang_analytics_android_api_agent_JMMIClick__", (args, methodResult) -> {
            Log.d("ObjectFactory", "创建对象: cn_jiguang_analytics_android_api_agent_JMMIClick__");
        
            // args
        
        
            // create target object
            cn.jiguang.analytics.android.api.agent.JMMIClick obj = new cn.jiguang.analytics.android.api.agent.JMMIClick();
            getHEAP().put(obj.hashCode(), obj);
        
            // print current HEAP
            if (getEnableLog()) {
                Log.d("ObjectFactory", "HEAP: " + getHEAP());
            }
        
            methodResult.success(obj.hashCode());
        });
        // factory
        put("ObjectFactory::createcn_jiguang_analytics_android_api_Account__String", (args, methodResult) -> {
            Log.d("ObjectFactory", "创建对象: cn_jiguang_analytics_android_api_Account__String");
        
            // args
            // jsonable arg
            String var1 = (String) args.get("var1");
        
            // create target object
            cn.jiguang.analytics.android.api.Account obj = new cn.jiguang.analytics.android.api.Account(var1);
            getHEAP().put(obj.hashCode(), obj);
        
            // print current HEAP
            if (getEnableLog()) {
                Log.d("ObjectFactory", "HEAP: " + getHEAP());
            }
        
            methodResult.success(obj.hashCode());
        });
        // factory
        put("ObjectFactory::createcn_jiguang_analytics_android_api_aop_JAct__", (args, methodResult) -> {
            Log.d("ObjectFactory", "创建对象: cn_jiguang_analytics_android_api_aop_JAct__");
        
            // args
        
        
            // create target object
            cn.jiguang.analytics.android.api.aop.JAct obj = new cn.jiguang.analytics.android.api.aop.JAct();
            getHEAP().put(obj.hashCode(), obj);
        
            // print current HEAP
            if (getEnableLog()) {
                Log.d("ObjectFactory", "HEAP: " + getHEAP());
            }
        
            methodResult.success(obj.hashCode());
        });
        // factory
        put("ObjectFactory::createcn_jiguang_analytics_android_api_aop_JMMIAgent__", (args, methodResult) -> {
            Log.d("ObjectFactory", "创建对象: cn_jiguang_analytics_android_api_aop_JMMIAgent__");
        
            // args
        
        
            // create target object
            cn.jiguang.analytics.android.api.aop.JMMIAgent obj = new cn.jiguang.analytics.android.api.aop.JMMIAgent();
            getHEAP().put(obj.hashCode(), obj);
        
            // print current HEAP
            if (getEnableLog()) {
                Log.d("ObjectFactory", "HEAP: " + getHEAP());
            }
        
            methodResult.success(obj.hashCode());
        });
        // factory
        put("ObjectFactory::createcn_analytics_client_android_BuildConfig__", (args, methodResult) -> {
            Log.d("ObjectFactory", "创建对象: cn_analytics_client_android_BuildConfig__");
        
            // args
        
        
            // create target object
            cn.analytics.client.android.BuildConfig obj = new cn.analytics.client.android.BuildConfig();
            getHEAP().put(obj.hashCode(), obj);
        
            // print current HEAP
            if (getEnableLog()) {
                Log.d("ObjectFactory", "HEAP: " + getHEAP());
            }
        
            methodResult.success(obj.hashCode());
        });
    }};

    // v1 android embedding for compatible
    public static void registerWith(Registrar registrar) {
        final MethodChannel channel = new MethodChannel(registrar.messenger(), "me.yohom/janalytics_fluttify");

        JanalyticsFluttifyPlugin plugin = new JanalyticsFluttifyPlugin();
        plugin.messenger = registrar.messenger();

        channel.setMethodCallHandler(plugin);

        // register platform view
        
    }

    // v2 android embedding
    @Override
    public void onAttachedToEngine(FlutterPluginBinding binding) {
        final MethodChannel channel = new MethodChannel(binding.getBinaryMessenger(), "me.yohom/janalytics_fluttify");

        messenger = binding.getBinaryMessenger();

        channel.setMethodCallHandler(this);

        // register platform view
        
    }

    @Override
    public void onDetachedFromEngine(FlutterPluginBinding binding) {

    }

    @Override
    public void onMethodCall(@NonNull MethodCall methodCall, @NonNull MethodChannel.Result methodResult) {
        Map<String, Object> args = (Map<String, Object>) methodCall.arguments;
        Handler handler = handlerMap.get(methodCall.method);
        if (handler != null) {
            try {
                handler.call(args, methodResult);
            } catch (Exception e) {
                e.printStackTrace();
                methodResult.error(e.getMessage(), null, null);
            }
        } else {
            methodResult.notImplemented();
        }
    }

    @FunctionalInterface
    interface Handler {
        void call(Map<String, Object> args, MethodChannel.Result methodResult) throws Exception;
    }
}
