// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:janalytics_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class JANALYTICSLaunchConfig extends NSObject  {
  //region constants
  static const String name__ = 'JANALYTICSLaunchConfig';

  @override
  final String tag__ = 'janalytics_fluttify';

  
  //endregion

  //region creators
  static Future<JANALYTICSLaunchConfig> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod(
      'ObjectFactory::createJANALYTICSLaunchConfig',
      {'init': init}
    );
    return JanalyticsFluttifyIOSAs<JANALYTICSLaunchConfig>(__result__);
  }
  
  static Future<List<JANALYTICSLaunchConfig>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kJanalyticsFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchJANALYTICSLaunchConfig',
      {'length': length, 'init': init}
    );
    return __result_batch__
        .map((it) => JanalyticsFluttifyIOSAs<JANALYTICSLaunchConfig>(it))
        .toList();
  }
  
  //endregion

  //region getters
  Future<String> get_appKey() async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLaunchConfig::get_appKey", {'__this__': this});
    return __result__;
  }
  
  Future<String> get_channel() async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLaunchConfig::get_channel", {'__this__': this});
    return __result__;
  }
  
  Future<String> get_advertisingId() async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLaunchConfig::get_advertisingId", {'__this__': this});
    return __result__;
  }
  
  Future<bool> get_isProduction() async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLaunchConfig::get_isProduction", {'__this__': this});
    return __result__;
  }
  
  //endregion

  //region setters
  Future<void> set_appKey(String appKey) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLaunchConfig::set_appKey', <String, dynamic>{'__this__': this, "appKey": appKey});
  
  
  }
  
  Future<void> set_channel(String channel) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLaunchConfig::set_channel', <String, dynamic>{'__this__': this, "channel": channel});
  
  
  }
  
  Future<void> set_advertisingId(String advertisingId) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLaunchConfig::set_advertisingId', <String, dynamic>{'__this__': this, "advertisingId": advertisingId});
  
  
  }
  
  Future<void> set_isProduction(bool isProduction) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLaunchConfig::set_isProduction', <String, dynamic>{'__this__': this, "isProduction": isProduction});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'JANALYTICSLaunchConfig{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension JANALYTICSLaunchConfig_Batch on List<JANALYTICSLaunchConfig> {
  //region getters
  Future<List<String>> get_appKey_batch() async {
    final resultBatch = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLaunchConfig::get_appKey_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => __result__)?.cast<String>()?.toList();
  }
  
  Future<List<String>> get_channel_batch() async {
    final resultBatch = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLaunchConfig::get_channel_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => __result__)?.cast<String>()?.toList();
  }
  
  Future<List<String>> get_advertisingId_batch() async {
    final resultBatch = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLaunchConfig::get_advertisingId_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => __result__)?.cast<String>()?.toList();
  }
  
  Future<List<bool>> get_isProduction_batch() async {
    final resultBatch = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLaunchConfig::get_isProduction_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => __result__)?.cast<bool>()?.toList();
  }
  
  //endregion

  //region setters
  Future<void> set_appKey_batch(List<String> appKey) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLaunchConfig::set_appKey_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "appKey": appKey[__i__]}]);
  
  
  }
  
  Future<void> set_channel_batch(List<String> channel) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLaunchConfig::set_channel_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "channel": channel[__i__]}]);
  
  
  }
  
  Future<void> set_advertisingId_batch(List<String> advertisingId) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLaunchConfig::set_advertisingId_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "advertisingId": advertisingId[__i__]}]);
  
  
  }
  
  Future<void> set_isProduction_batch(List<bool> isProduction) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLaunchConfig::set_isProduction_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "isProduction": isProduction[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}