// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:janalytics_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class JANALYTICSLoginEvent extends JANALYTICSEventObject  {
  //region constants
  static const String name__ = 'JANALYTICSLoginEvent';

  @override
  final String tag__ = 'janalytics_fluttify';

  
  //endregion

  //region creators
  static Future<JANALYTICSLoginEvent> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod(
      'ObjectFactory::createJANALYTICSLoginEvent',
      {'init': init}
    );
    return JanalyticsFluttifyIOSAs<JANALYTICSLoginEvent>(__result__);
  }
  
  static Future<List<JANALYTICSLoginEvent>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kJanalyticsFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchJANALYTICSLoginEvent',
      {'length': length, 'init': init}
    );
    return __result_batch__
        .map((it) => JanalyticsFluttifyIOSAs<JANALYTICSLoginEvent>(it))
        .toList();
  }
  
  //endregion

  //region getters
  Future<String> get_method() async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLoginEvent::get_method", {'__this__': this});
    return __result__;
  }
  
  Future<bool> get_success() async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLoginEvent::get_success", {'__this__': this});
    return __result__;
  }
  
  //endregion

  //region setters
  Future<void> set_method(String method) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLoginEvent::set_method', <String, dynamic>{'__this__': this, "method": method});
  
  
  }
  
  Future<void> set_success(bool success) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLoginEvent::set_success', <String, dynamic>{'__this__': this, "success": success});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'JANALYTICSLoginEvent{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension JANALYTICSLoginEvent_Batch on List<JANALYTICSLoginEvent> {
  //region getters
  Future<List<String>> get_method_batch() async {
    final resultBatch = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLoginEvent::get_method_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => __result__)?.cast<String>()?.toList();
  }
  
  Future<List<bool>> get_success_batch() async {
    final resultBatch = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSLoginEvent::get_success_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => __result__)?.cast<bool>()?.toList();
  }
  
  //endregion

  //region setters
  Future<void> set_method_batch(List<String> method) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLoginEvent::set_method_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "method": method[__i__]}]);
  
  
  }
  
  Future<void> set_success_batch(List<bool> success) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSLoginEvent::set_success_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "success": success[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}