// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum JANALYTICSPurchaseCurrency {
  JANALYTICSCurrencyCNY /* null */,
  JANALYTICSCurrencyUSD /* null */
}

extension JANALYTICSPurchaseCurrencyToX on JANALYTICSPurchaseCurrency {
  int toValue() {
    switch (this) {
      case JANALYTICSPurchaseCurrency.JANALYTICSCurrencyCNY: return JANALYTICSPurchaseCurrency.JANALYTICSCurrencyCNY.index + 0;
      case JANALYTICSPurchaseCurrency.JANALYTICSCurrencyUSD: return JANALYTICSPurchaseCurrency.JANALYTICSCurrencyUSD.index + 0;
    }
  }
}

extension JANALYTICSPurchaseCurrencyFromX on int {
  JANALYTICSPurchaseCurrency toJANALYTICSPurchaseCurrency() {
    switch (this) {
      
      default: return JANALYTICSPurchaseCurrency.values[this + 0];
    }
  }
}