// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:janalytics_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class JANALYTICSEventObject extends NSObject  {
  //region constants
  static const String name__ = 'JANALYTICSEventObject';

  @override
  final String tag__ = 'janalytics_fluttify';

  
  //endregion

  //region creators
  static Future<JANALYTICSEventObject> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod(
      'ObjectFactory::createJANALYTICSEventObject',
      {'init': init}
    );
    return JanalyticsFluttifyIOSAs<JANALYTICSEventObject>(__result__);
  }
  
  static Future<List<JANALYTICSEventObject>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kJanalyticsFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchJANALYTICSEventObject',
      {'length': length, 'init': init}
    );
    return __result_batch__
        .map((it) => JanalyticsFluttifyIOSAs<JANALYTICSEventObject>(it))
        .toList();
  }
  
  //endregion

  //region getters
  Future<Map<String,String>> get_extra() async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSEventObject::get_extra", {'__this__': this});
    return __result__;
  }
  
  //endregion

  //region setters
  Future<void> set_extra(Map<String,String> extra) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSEventObject::set_extra', <String, dynamic>{'__this__': this, "extra": extra});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion

  @override
  String toString() {
    return 'JANALYTICSEventObject{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension JANALYTICSEventObject_Batch on List<JANALYTICSEventObject> {
  //region getters
  Future<List<Map<String,String>>> get_extra_batch() async {
    final resultBatch = await kJanalyticsFluttifyChannel.invokeMethod("JANALYTICSEventObject::get_extra_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => __result__)?.cast<Map<String,String>>()?.toList();
  }
  
  //endregion

  //region setters
  Future<void> set_extra_batch(List<Map<String,String>> extra) async {
    await kJanalyticsFluttifyChannel.invokeMethod('JANALYTICSEventObject::set_extra_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "extra": extra[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}