// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:janalytics_fluttify/src/ios/ios.export.g.dart';
import 'package:janalytics_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class JANALYTICSUserInfo extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<JANALYTICSUserInfo> create__() async {
    final int refId = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('ObjectFactory::createJANALYTICSUserInfo');
    final object = JANALYTICSUserInfo()..refId = refId..tag = 'janalytics_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  //endregion

  //region getters
  Future<String> get_accountID() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_accountID", {'refId': refId});
  
    return result;
  }
  
  Future<JANALYTICSSex> get_sex() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_sex", {'refId': refId});
  
    return JANALYTICSSex.values[result];
  }
  
  Future<String> get_birthdate() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_birthdate", {'refId': refId});
  
    return result;
  }
  
  Future<JANALYTICSPaid> get_paid() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_paid", {'refId': refId});
  
    return JANALYTICSPaid.values[result];
  }
  
  Future<String> get_phone() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_phone", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_email() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_email", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_name() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_name", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_wechatID() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_wechatID", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_qqID() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_qqID", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_weiboID() async {
    final result = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod("JANALYTICSUserInfo::get_weiboID", {'refId': refId});
  
    return result;
  }
  
  //endregion

  //region setters
  Future<void> set_accountID(String accountID) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_accountID', {'refId': refId, "accountID": accountID});
  
  
  }
  
  Future<void> set_sex(JANALYTICSSex sex) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_sex', {'refId': refId, "sex": sex.index});
  
  
  }
  
  Future<void> set_birthdate(String birthdate) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_birthdate', {'refId': refId, "birthdate": birthdate});
  
  
  }
  
  Future<void> set_paid(JANALYTICSPaid paid) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_paid', {'refId': refId, "paid": paid.index});
  
  
  }
  
  Future<void> set_phone(String phone) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_phone', {'refId': refId, "phone": phone});
  
  
  }
  
  Future<void> set_email(String email) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_email', {'refId': refId, "email": email});
  
  
  }
  
  Future<void> set_name(String name) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_name', {'refId': refId, "name": name});
  
  
  }
  
  Future<void> set_wechatID(String wechatID) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_wechatID', {'refId': refId, "wechatID": wechatID});
  
  
  }
  
  Future<void> set_qqID(String qqID) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_qqID', {'refId': refId, "qqID": qqID});
  
  
  }
  
  Future<void> set_weiboID(String weiboID) async {
    await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('JANALYTICSUserInfo::set_weiboID', {'refId': refId, "weiboID": weiboID});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}