// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:janalytics_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class cn_jiguang_analytics_android_view_BuryWebActivity extends android_app_Activity  {
  //region constants
  static const String name__ = 'cn.jiguang.analytics.android.view.BuryWebActivity';

  @override
  final String tag__ = 'janalytics_fluttify';

  
  //endregion

  //region creators
  static Future<cn_jiguang_analytics_android_view_BuryWebActivity> create__() async {
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod(
      'ObjectFactory::createcn_jiguang_analytics_android_view_BuryWebActivity__',
    
    );
    return JanalyticsFluttifyAndroidAs<cn_jiguang_analytics_android_view_BuryWebActivity>(__result__);
  }
  
  static Future<List<cn_jiguang_analytics_android_view_BuryWebActivity>> create_batch__(int length) async {
    assert(true);
    final __result_batch__ = await  kJanalyticsFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchcn_jiguang_analytics_android_view_BuryWebActivity__',
      {'length': length}
    );
    return __result_batch__
        .map((it) => JanalyticsFluttifyAndroidAs<cn_jiguang_analytics_android_view_BuryWebActivity>(it))
        .toList();
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<void> onBackPressed() async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: cn.jiguang.analytics.android.view.BuryWebActivity@$refId::onBackPressed([])');
    }
  
    // invoke native method
    final __result__ = await kJanalyticsFluttifyChannel.invokeMethod('cn.jiguang.analytics.android.view.BuryWebActivity::onBackPressed', {"__this__": this});
  
  
    // handle native call
  
  
    return __result__;
  }
  
  //endregion

  @override
  String toString() {
    return 'cn_jiguang_analytics_android_view_BuryWebActivity{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension cn_jiguang_analytics_android_view_BuryWebActivity_Batch on List<cn_jiguang_analytics_android_view_BuryWebActivity> {
  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  Future<List<void>> onBackPressed_batch() async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kJanalyticsFluttifyChannel.invokeMethod('cn.jiguang.analytics.android.view.BuryWebActivity::onBackPressed_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => __result__).cast<void>().toList();
  }
  
  //endregion
}