// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:janalytics_fluttify/src/ios/ios.export.g.dart';
import 'package:janalytics_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class cn_analytics_client_android_BuildConfig extends java_lang_Object  {
  //region constants
  static final String APPLICATION_ID = "cn.analytics.client.android";
  static final String BUILD_TYPE = "release";
  static final String FLAVOR = "";
  static final int VERSION_CODE = 1;
  static final String VERSION_NAME = "2.1.0";
  //endregion

  //region creators
  static Future<cn_analytics_client_android_BuildConfig> create__() async {
    final int refId = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('ObjectFactory::createcn_analytics_client_android_BuildConfig__');
    final object = cn_analytics_client_android_BuildConfig()..refId = refId..tag = 'janalytics_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<cn_analytics_client_android_BuildConfig>> create_batch__(int length) async {
    // if (#__check_param_size__#) {
    //   return Future.error('all args must has same length!');
    // }
    final List resultBatch = await MethodChannel('me.yohom/janalytics_fluttify').invokeMethod('ObjectFactory::create_batchcn_analytics_client_android_BuildConfig__', {'length': length});
  
    final List<cn_analytics_client_android_BuildConfig> typedResult = resultBatch.map((result) => cn_analytics_client_android_BuildConfig()..refId = result..tag = 'janalytics_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}

extension cn_analytics_client_android_BuildConfig_Batch on List<cn_analytics_client_android_BuildConfig> {
  //region getters
  
  //endregion

  //region methods
  
  //endregion
}